# AUTO RELEASE BASED ON A TAG NAME. IT REQUIRES A TAG ALREADY CREATED.

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
    release:
      name: "Release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{secrets.GITHUB_TOKEN}}"
            prerelease: false
