# AUTO GENERATE CHANGELOG FOR TAGS, ISSUES, LABELS AND PULL REQUESTS

name: Changelog-generator

# on:
#   release:
#     types:
#       - created

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 