# AUTO RELEASE BASED ON A TAG NAME. IT REQUIRES A TAG ALREADY CREATED. TAGS WITH "b" SUFFIX
# WILL NOT BE CONSIDERED.

name: Release

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
    release:
      name: "Release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.client_payload.sha }}
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: 'Get Previous tag'
          id: gettag
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
          with:
            fallback: latest
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            automatic_release_tag: "{{ steps.gettag.output.tag }}"
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
