# AUTO RELEASE EXCLUDING BETA/EXPERIMENTAL/QA POSTS BASED ON MAIN BRANCH

name: Release

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    tags:
      - "v*"

jobs:
    release:
      name: "Release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: ${env.GITHUB_TOKEN}
            prerelease: false
