# AUTO RELEASE BASED ON A TAG NAME. IT REQUIRES A TAG ALREADY CREATED. TAGS WITH "b" SUFFIX
# WILL NOT BE CONSIDERED.

name: Release

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
    release:
      name: "Release"
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.client_payload.sha }}
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            automatic_release_tag: "latest"
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
