# AUTO TAG BASED ON PUSH TO A BRANCH. AUTO RELEASE BASED ON A NON-BETA/TEST TAG.
# REQUIRES PACKAGE.JSON WITH "version" PROPERTY UNDER SEMANTIC VERSIONING. ADDING
# "b" SUFFIX IN THE VERSION IN "version" PROPERTY DEFINES A BETA/TEST TAG.

name: Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Extract version
        id: get-package-version
        uses: jaywcjlove/github-action-package@main

      - name: Printing package version
        run: echo ${{ steps.get-package-version.outputs.version }}

      - name: "Gathering tag name removing timestamp"
        if: "!contains(steps.get-package-version.outputs.version, 'beta')"
        id: get-ver
        run: |
          ver=$(echo ${{ steps.get-package-version.outputs.version }} | cut -d- -f1)
          echo "::set-output name=ver::$ver"

      - name: Printing tag and release version
        run: echo "${{ steps.get-ver.outputs.ver }}"

      - name: Checkout code
        if: "!contains(steps.get-package-version.outputs.version, 'beta')"
        uses: actions/checkout@v2

      - name: Generating Tag
        if: "!contains(steps.get-package-version.outputs.version, 'beta')"
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          version:
            "${{ steps.get-ver.outputs.ver }}"
            # tag_prefix: "v"
            # tag_suffix: "b"
        # - name: Trigger next workflow
        #   if: "success() && !contains(steps.get-tag.outputs.tag, 'beta')"
        #   uses: peter-evans/repository-dispatch@v1
        #   with:
        #     token: ${{ secrets.REPO_GHA_PAT }}
        #     repository: ${{ github.repository }}
        #     event-type: actions-release
        #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
