# AUTO TAG BASED ON A BRANCH. IT REQUIRES A PACKAGE.JSON FILE IN THE PROJECT ROOT
# TO WORK. THE VERSION WILL BE READ FROM THE "version" PROPERTY IN THE FILE.

name: Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
        tag_suffix: ! "b"